name: pcb_image
on:
    push:
jobs:
    render-image:
        name: render-image
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Fonts
          run: |
            wget -O Inter.zip https://github.com/rsms/inter/releases/download/v4.0/Inter-4.0.zip
            unzip -d inter/ Inter.zip
            mv inter /usr/share/fonts/
            wget -O Monaspace.zip https://github.com/githubnext/monaspace/releases/download/v1.000/monaspace-v1.000.zip
            unzip -d monaspace/ Monaspace.zip
            mv monaspace /usr/share/fonts/
            fc-cache -fv

        - name: Render PCB Image
          uses: linalinn/kicad-render@main
          with:
            pcb_file: tallytime.kicad_pcb
            output_path: ${{ github.workspace }}/images

        - name: Setup Pages
          if: github.ref == 'refs/heads/main'
          uses: actions/configure-pages@v5.0.0

        - name: Upload Artifact
          if: github.ref == 'refs/heads/main'
          uses: actions/upload-pages-artifact@v3.0.1
          with:
            path: "images"

    deploy-pages:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: render-image

        permissions:
          pages: write
          id-token: write

        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}

        steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
